# Generated by Django 4.2 on 2023-04-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Service', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuponCode', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('startAt', models.DateTimeField()),
                ('expiredAt', models.DateTimeField()),
                ('minimumSpend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discountType', models.CharField(choices=[('percent', 'Percent'), ('amount', 'Amount')], max_length=10)),
                ('discountAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicesOffered', models.ManyToManyField(related_name='couponOnServices', to='Service.serviceoffered')),
            ],
        ),
    ]
