# Generated by Django 4.2 on 2023-04-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cupon', '0001_initial'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_gateway', models.CharField(choices=[('cash', 'Cash'), ('ewallet', 'E-Wallet'), ('fonepay', 'Fonepay'), ('card', 'Card')], max_length=20)),
                ('payment_key', models.CharField(max_length=50)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymentCupon', to='Cupon.cupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentForOrder', to='Order.order')),
            ],
        ),
    ]
