# Generated by Django 4.2 on 2023-04-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Salon', '0001_initial'),
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icons/')),
                ('iconName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('icon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='serviceIcon', to='Service.icon')),
            ],
        ),
        migrations.CreateModel(
            name='serviceOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, null=True)),
                ('estimated_time', models.DurationField(blank=True, null=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceOfferedBySalon', to='Salon.salon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicesOffered', to='Service.service')),
                ('serviceImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceImage', to='Salon.salonimage')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceOfferedByStaff', to='Staff.staff')),
            ],
        ),
    ]
