# Generated by Django 4.2 on 2023-04-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Service', '0001_initial'),
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('ARRIVED', 'Arrived'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='BOOKED', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderByClient', to='Client.client')),
                ('service_offered', models.ManyToManyField(related_name='servicesOrdered', to='Service.serviceoffered')),
            ],
        ),
    ]
